feat: add advertisement info
frontendkz/rules pull request #2
Opened 2022-11-28 13:41 UTC by drugoi

2022-11-29 10:15 UTC, roose requested changes

2022-11-29 10:15 UTC, roose commented on README.md
> +* Стоимость размещения 1-го (одного) поста с закреплением его (pin) на неделю — **40 000 KZT** _(сорок тысяч тенге)_.
мб "его" убрать вообще?

2022-11-29 10:32 UTC, talgautb commented on README.md
> +Размещение рекламных постов возможно только по **фронтенд** направлению, в исключительных случаях возможно размещение рекламы связанной с IT и косвенно с фронтендом (например: курсы по Node.js).
>в исключительных случаях возможно размещение рекламы связанной с IT и косвенно с фронтендом (например: курсы по Node.js).

в 1 предложении дублируется слова, может так:
`в исключительных случаях с IT и косвенно с фронтендом (например: курсы по Node.js).`

2022-11-29 10:32 UTC, talgautb commented on README.md
> +**Размещение производится от лица сообщества Frontend KZ.**
А что значит? мы будем публиковать от сообщества?

2022-11-29 10:32 UTC, talgautb commented on README.md
> +Для размещения рекламы, получения реквизитов на оплату и статистики по сообществу — просьба обратиться к любому из администраторов сообщества: [Руслан](https://t.me/iamroose), [Никита](https://t.me/d
можно просто без ссылок и никнеймов) в чате найдут, а то если меняться/добавляться будут то каждый раз редактировать. либо определить пару ответственных бухгалтеров группы :)

2022-11-29 10:33 UTC, drugoi commented on README.md
> +**Размещение производится от лица сообщества Frontend KZ.**
@talgautb да, под фейк-логином.

2022-11-29 10:33 UTC, drugoi commented on README.md
> +Для размещения рекламы, получения реквизитов на оплату и статистики по сообществу — просьба обратиться к любому из администраторов сообщества: [Руслан](https://t.me/iamroose), [Никита](https://t.me/d
Можем ограничить кому писать.

2022-11-29 10:33 UTC, talgautb commented on README.md
> +* Стоимость размещения 1-го (одного) поста с закреплением его (pin) на неделю — **40 000 KZT** _(сорок тысяч тенге)_.
и добавить ₸ вместо кзт :)

2022-11-29 10:35 UTC, talgautb commented on README.md
> +Для размещения рекламы, получения реквизитов на оплату и статистики по сообществу — просьба обратиться к любому из администраторов сообщества: [Руслан](https://t.me/iamroose), [Никита](https://t.me/d
Если всем из 4х ок, можно оставить.

2022-12-06 02:49 UTC, talgautb approved these changes

2022-12-06 08:58 UTC, merged